### ISSUE TITLE
Error running on Azure: The specified CGI application encountered an error

### ISSUE THREAD

**Issue by evilripper** [HakanL/DinkToPdf#10] opened 2019-07-27 09:50 UTC
I'm using DinkToPdf on a net core app 2.1 but it works only in local pc. :(

On azure WEB APP:
The specified CGI application encountered an error and the server terminated the process.

In Application Insights there is nothing!!! -_- 

Have any idea?

**Comment by HakanL** [comment] 2019-07-30 12:45
Seems to be a duplicate of #8, but we don't have a good solution for it yet.

**Comment by evilripper** [comment] 2019-08-02 12:48
For now I am using a VM and with IIS it works like a charm, the sandbox of web app sucks! -_-

**Comment by HakanL** [comment] 2019-08-03 08:24
It's most likely an issue with the sandbox now allowing the native C library. If I find some time to test it out I'll see what I can do, but hopefully somebody else can figure it out (short of re-adding the binaries).

**Comment by HakanL** [comment] 2020-01-15 15:53
I'm running a Web App in Azure, 64-bit .NET Core 3.1 in an S2 App Service Plan and DinkToPdf is working fine. It may not be possible to run in a consumption plan, or Azure function, but in a regular plan it seems to work fine, at least in 64-bit.

**Closed by HakanL** 2020-01-15 15:53 UTC
